name: API CI
on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'

defaults:
  runs:
    working-directory: ./api

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install Dependencies
        shell: bash
        run: npm ci
      - name: Run Unit Tests
        shell: bash
        run: npm run test

  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:16
    Services:
      mongo-e2e:
        image: mongo:4.4
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root123

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        shell: bash
        run: npm ci
      - name: Run E2E Tests
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb://root:root123@localhost:27017?retryWrites=true&writeConcern=majority
